### PR TITLE
Handle solutions that don't compile (fixes #21)

### LINKED ISSUE #21: Don't crash if compilation fails
I've noticed that Exalysis crashes if the solution doesn't compile. It would be nice if it said something like "Unfortunately your solution does not compile. Here is the error message..."

### PR DESCRIPTION
**Pull request by bitfield**
Right now if a solution doesn't compile, Exalysis bails out with a fatal error. This PR allows Exalysis to handle the situation, returning a friendly message to the student about what went wrong.

### CODE REVIEW

File: cmd/exalysis/main_test.go [hunk 1]
```diff
@@ -0,0 +1,45 @@
+package main
```
Comment (bitfield) [inline cmd/exalysis/main_test.go]: Strictly speaking I could have added a test for this to one of the track tests, but I thought it might be useful to be able to test running the executable, too.

File: gtpl/tools/compile.md [hunk 2]
```diff
@@ -0,0 +1 @@
+- Unfortunately, this solution does not compile correctly. Did you run the tests? Maybe you accidentally submitted an incomplete solution? If you're having trouble getting your program to compile, you can always ask me for help!
```
Comment (bitfield) [inline gtpl/tools/compile.md]: We could include the error message here, but we don't do that for test failures, so maybe it's better to encourage the student to find the error for themselves.
